# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.EmailField(max_length=254)),
                ('account_added_at', models.DateTimeField()),
                ('inactive', models.CharField(max_length=1)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('summ', models.DecimalField(decimal_places=2, max_digits=8)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Account')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephoneNum1', models.CharField(max_length=11)),
                ('telephoneNum2', models.CharField(max_length=11)),
                ('telephoneNum3', models.CharField(max_length=11)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=40)),
                ('middleName', models.CharField(max_length=40)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Legal_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_ID', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('company_name', models.CharField(max_length=40)),
                ('BIN', models.CharField(max_length=12)),
                ('bank_account', models.CharField(max_length=25)),
                ('bank', models.CharField(max_length=20)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_or_email', models.CharField(choices=[(b'call', b'\xd0\xb7\xd0\xb2\xd0\xbe\xd0\xbd\xd0\xbe\xd0\xba'), (b'email', b'\xd0\xb7\xd0\xb0\xd1\x8f\xd0\xb2\xd0\xba\xd0\xb0')], max_length=5)),
                ('status', models.CharField(choices=[(b'INTS', b'\xd0\xb7\xd0\xb0\xd0\xb8\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80\xd0\xb5\xd1\x81\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c'), (b'EVAL', b'\xd0\xbe\xd1\x86\xd0\xb5\xd0\xbd\xd0\xba\xd0\xb0'), (b'OFER', b'\xd0\xbf\xd1\x80\xd0\xb5\xd0\xb4\xd0\xbb\xd0\xbe\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'), (b'BILL', b'\xd0\xb2\xd1\x8b\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd \xd1\x81\xd1\x87\xd0\xb5\xd1\x82'), (b'PROC', b'\xd0\xb2\xd1\x8b\xd0\xbf\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xb7\xd0\xb0\xd0\xba\xd0\xb0\xd0\xb7\xd0\xb0'), (b'DONE', b'\xd0\xb7\xd0\xb0\xd0\xba\xd0\xb0\xd0\xb7 \xd0\xb2\xd1\x8b\xd0\xbf\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xb5\xd0\xbd'), (b'FAIL', b'\xd0\xbe\xd1\x82\xd0\xba\xd0\xb0\xd0\xb7')], max_length=20)),
                ('call_on', models.DateField(blank=True)),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('client_contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientContactDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Order_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('step_description', models.TextField()),
                ('date_step', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Order')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='clientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
    ]
