# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 06:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='legal_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_ID', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=40)),
                ('BIN', models.CharField(max_length=12)),
                ('bank_account', models.CharField(max_length=25)),
                ('bank', models.CharField(max_length=20)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cleintId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.AlterField(
            model_name='clientcontactdetails',
            name='telephoneNum1',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='clientcontactdetails',
            name='telephoneNum2',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='clientcontactdetails',
            name='telephoneNum3',
            field=models.CharField(max_length=11),
        ),
    ]
