# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20160514_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='author',
        ),
        migrations.RemoveField(
            model_name='account',
            name='clientId',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='account',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='author',
        ),
        migrations.AddField(
            model_name='client',
            name='LK',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='account_added_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='inactive',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'INTS', b'\xd0\xb7\xd0\xb0\xd0\xb8\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80\xd0\xb5\xd1\x81\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c'), (b'EVAL', b'\xd0\xbe\xd1\x86\xd0\xb5\xd0\xbd\xd0\xba\xd0\xb0'), (b'OFER', b'\xd0\xbf\xd1\x80\xd0\xb5\xd0\xb4\xd0\xbb\xd0\xbe\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'), (b'BILL', b'\xd0\xb2\xd1\x8b\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd \xd1\x81\xd1\x87\xd0\xb5\xd1\x82'), (b'PROC', b'\xd0\xb2\xd1\x8b\xd0\xbf\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xb7\xd0\xb0\xd0\xba\xd0\xb0\xd0\xb7\xd0\xb0'), (b'DONE', b'\xd0\xb7\xd0\xb0\xd0\xba\xd0\xb0\xd0\xb7 \xd0\xb2\xd1\x8b\xd0\xbf\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xb5\xd0\xbd'), (b'FAIL', b'\xd0\xbe\xd1\x82\xd0\xba\xd0\xb0\xd0\xb7')], default=b'INTS', max_length=20),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
