# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20160426_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_proces',
            new_name='Order_process',
        ),
        migrations.AlterField(
            model_name='order',
            name='client_contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientContactDetails'),
        ),
    ]
