# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20160713_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontactdetails',
            name='telephoneNum1',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='clientcontactdetails',
            name='telephoneNum2',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='clientcontactdetails',
            name='telephoneNum3',
            field=models.CharField(max_length=16),
        ),
    ]
