# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20160510_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legal_details',
            old_name='cleintId',
            new_name='clientId',
        ),
        migrations.AlterField(
            model_name='billing',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientContactDetails'),
        ),
    ]
