# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20160715_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
