# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 16:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20160514_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call_on',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 5, 14, 16, 15, 0, 3404)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientContactDetails'),
        ),
    ]
