# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_persons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legal_details',
            old_name='clientId',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='legal_details',
            name='BIN',
        ),
        migrations.RemoveField(
            model_name='legal_details',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='legal_details',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='legal_details',
            name='personal_ID',
        ),
    ]
