# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20160717_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='LK',
        ),
        migrations.RemoveField(
            model_name='client',
            name='account_added_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='client',
            name='inactive',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='client',
            name='middleName',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telephoneNum1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telephoneNum2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telephoneNum3',
        ),
    ]
