# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_lk_changedon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lk',
            old_name='clientId',
            new_name='client',
        ),
    ]
