# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20160730_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lk',
            name='LK_added_at',
            field=models.DateField(),
        ),
    ]
