# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_auto_20160730_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legal_details',
            name='addedAt',
        ),
        migrations.AddField(
            model_name='legal_details',
            name='changedOn',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
