# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_auto_20160731_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_contacts',
        ),
    ]
