# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_remove_order_client_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='clientId',
            new_name='client',
        ),
    ]
