# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_auto_20160803_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='changedOn',
            field=models.DateField(auto_now=True),
        ),
    ]
