# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_auto_20160803_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='telephoneNum1',
            field=models.CharField(default=b'', max_length=16),
        ),
        migrations.AlterField(
            model_name='persons',
            name='telephoneNum2',
            field=models.CharField(default=b'', max_length=16),
        ),
    ]
