# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0034_auto_20160821_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontactdetails',
            name='focalPoint',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='focalPoint',
        ),
    ]
