# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_auto_20160821_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='addedAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
