# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20160514_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='clientID',
            new_name='clientId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tel_or_email',
        ),
        migrations.AddField(
            model_name='order',
            name='call_or_email',
            field=models.CharField(choices=[(b'call', b'\xd0\xb7\xd0\xb2\xd0\xbe\xd0\xbd\xd0\xbe\xd0\xba'), (b'email', b'\xd0\xb7\xd0\xb0\xd1\x8f\xd0\xb2\xd0\xba\xd0\xb0')], default='call', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientContactDetails'),
        ),
    ]
