# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0015_auto_20160514_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='manager',
        ),
        migrations.AddField(
            model_name='order_process',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientContactDetails'),
        ),
    ]
